### ISSUE TITLE
Clicking on the LMHT/HTML logo sends you to the wrong place

### ISSUE THREAD

**Issue by ahaynes-ador** [kevinbrianfahy/LMHT#101]
It should send you to root (`/`). Right now, it sends you to `/LMHT`.

**Comment by ericanaughton** [comment]
fixed it - gonna add some other small fixes before the PR is ready https://github.com/adorableio/LMHT/pull/8

**Comment by ericanaughton** [comment]
PR is ready https://github.com/adorableio/LMHT/pull/8
