### ISSUE TITLE
Contributing.md fixes

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#102]
In order to know how I can contribute to LMHT,
As a contributor of LMHT,
I want to have quick access to the contributing details from the README and complete directions on how to run the project locally.

Acceptance Criteria:
- Link to CONTRIBUTING.md inside README works
- contributing.md is changed to CONTRIBUTING.md
- README contains details on running python for the working on the project

Given a contributor of LMHT,
When I visit the README,
I can click on the CONTRIBUTING.md link and be directed to the correct page,
And I am informed to run python to see the project locally.

**Comment by rylnd** [comment]
Please also rename the file to CONTRIBUTING.md, as that's the standard.

**Comment by ericanaughton** [comment]
@bigtiger test

**Comment by bigtiger** [comment]
This worked @ericanaughton

**Comment by kathyoleary** [comment]
https://github.com/adorableio/LMHT/pull/10  Posted a request for double thumbs.

**Comment by ericanaughton** [comment]
PR is merged
