### ISSUE TITLE
Make page load by pressing enter key

### ISSUE THREAD

**Issue by kathyoleary** [kevinbrianfahy/LMHT#103]
In order to search quickly and efficiently 
as a user of the LMHT website, 
I want to be able to type the name of the tag I'm looking for and hit enter 

Acceptance Criteria:
- Can type in tag name and hit enter to get the correct page

Given a user of the LMHT website
when I type in a tag's name and hit enter
the correct page opens up

**Comment by ericanaughton** [comment]
merged, pat gave a suggestion though https://github.com/adorableio/LMHT/pull/21
