### ISSUE TITLE
Spanish - Translations for Welcome Page

### ISSUE THREAD

**Issue by kathyoleary** [kevinbrianfahy/LMHT#104]
In order to know how to use the LMHT page
as a spanish speaking user
I want a welcome page that shows me how to use the page in spanish

Acceptance Criteria:
- Welcome page shows up when page opens
- Tells how to use the web page in spanish

Given a Spanish user
When I go to the LMHT web page
A welcome window should open
And give me the basic instructions on how to use the page effectively.

English part of welcome.html has already been created and awaiting approval https://github.com/adorableio/LMHT/pull/9

**Comment by kathyoleary** [comment]
emailed Sandra Maly the english content for her to translate.  She agreed over the weekend to help translate whatever I email to her.  Woot!

**Comment by kathyoleary** [comment]
Sent Jennifer Sandra's email so she can resent the updated Welcome info to her.

**Comment by ericanaughton** [comment]
merged
