### ISSUE TITLE
Spanish translation placeholders

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#105]
In order to know I can contribute,
As a Spanish speaking LMHT user,
I want to see a message in empty areas that let me know I can contribute translations.

Acceptance Criteria:
- A message is written English and Spanish
- The message is placed in any unfinished area
- The message inform the user that the section is incomplete and needs help from contributors.

Given a Spanish speaking LMHT user,
When I see an empty section,
I want to know that I can contribute to make it more complete.

**Comment by kathyoleary** [comment]
Need to have something in place when we only have english side of definitions done, not a temporary translation, but something that says we need help with translations.

**Comment by ericanaughton** [comment]
wrote it in the wiki, jen will translate it there.

https://github.com/adorableio/LMHT/wiki

**Comment by ericanaughton** [comment]
Spanish translation is now in the wiki.
