### ISSUE TITLE
Research ribbon on sticky nav

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#115]
In order to know I can contribute
As a LMHT user
I want to see the 'Contribute' ribbon at all times

Acceptance Criteria:
- Ribbon is visible on the sticky nav, when you scroll down
- Ribbon works as a link to CONTRIBUTING.md

Given a LMHT user
When I go to the LMHT site
I want to easily see that I can contribute
And be directed to the instructions of how to contribute
From anywhere in the site.

**Comment by kathyoleary** [comment]
research and find examples of different types of bookmarks, where will it hang, what will it cover?
