### ISSUE TITLE
Determine next ten elements

### ISSUE THREAD

**Issue by kathyoleary** [kevinbrianfahy/LMHT#120]

**Comment by ericanaughton** [comment]
how's this coming along @kathyoleary ?

**Comment by kathyoleary** [comment]
Went through a "Learn HTML in 24 Hrs" Course and found what order they learned things in.  This would be the next group. I have a copy on my shared Google Drive:  https://docs.google.com/document/d/1dJNMCS8sJzYH46AEul7V2j16D_v5S83Fh4NgCMbcCII/edit

That doc has the ones we already loaded, then the next recommended, followed by the order of the rest for the 24 hr class and then the breakout listing that Erica had done broken out by type: element, tag, attribute, etc.

These are the next ten-ish....I say ten-ish because I grouped the h1-h6 as one and that makes 11 total for this list.

```
1)   <p>…</p>
A paragraph; skips a line between paragraphs.

2)  <h1>…</h1>
A first-level heading.
<h2>…</h2>
A second-level heading.
<h3>…</h3>
A third-level heading.
<h4>…</h4>
A fourth-level heading (seldom used).
<h5>…</h5>
A fifth-level heading (seldom used).
<h6>…</h6>
A sixth-level heading (seldom used).


3)  <div>…</div>
A region of text to be formatted.


4)  <ol>…</ol>
An ordered (numbered) list.

5)  <ul>…</ul>
An unordered (bulleted) list.
6)  <li>…</li>
A list item for use with <ol> or <ul>.


7)  <em>…</em>
Emphasis (usually italic).

8)  <strong>…</strong>
Stronger emphasis (usually bold).

9)  <b>…</b>
Boldface text.
10)  <i>…</i>
Italic text.

11)  <font>…</font>
Controls the appearance of the enclosed text.
```
