### ISSUE TITLE
Page auto scrolls up when element is selected

### ISSUE THREAD

**Issue by kathyoleary** [kevinbrianfahy/LMHT#124]
In order to use less of my time 
As a LMHT user
I want the page to automatically scroll up to where I can see all the content, when I select an element from the dropdown within the sticky nav.

Acceptance Criteria:
- When the new content loads, the page scrolls up to the beginning of the new content
- The transition is smooth

Given a LMHT user,
When I am scrolled down,
And sticky nav appears with the combobox in it,
And I select an element,
Then the page automatically scrolls up to where I can see all the new content displayed.

**Comment by ericanaughton** [comment]
merged to adorable master
