### ISSUE TITLE
add footer to enable auto scrolling

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#131]
Because of the different lengths of definitions, the pages are not all equal sizes. This effects the position to where the page scrolls up or down.

When the window is short enough (like the image below), the page will automatically scroll up to the top of the new content. 
![image](https://cloud.githubusercontent.com/assets/9439053/12042628/6e191a54-ae42-11e5-8290-0c43c4f086e5.png)

But if the window is expanded (like the picture below), the content hops down to the furthest point it can scroll, making it look jittery and inconsistent.
![image](https://cloud.githubusercontent.com/assets/9439053/12042641/99bf973c-ae42-11e5-9740-9d1367d44c7f.png)

Should we remove the scroll down feature?

**Comment by savance-ford** [comment]
Look at other sites with large footers for inspiration

**Comment by kathyoleary** [comment]
do we want to add https://github.com/LMHT/LMHT.github.io/issues/45 to this and put the links in the footer?

**Comment by kathyoleary** [comment]
yes, link with #45 per Jim

**Comment by kathyoleary** [comment]
https://github.com/adorableio/LMHT/pull/48  Put this through, it should be sufficient size to help the scroll issue.
