### ISSUE TITLE
Logo on sticky nav overlapped by search bar

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#134]
In order to see the entire logo when I scroll down
As a LMHT user
I want the logo to not be covered up by the search bar when my screen is small.

Acceptance Criteria:
- Logo is not covered up at any screen size

Given a LMHT user
When my screen is small and I scroll down
I see the entire logo on the sticky nav.

![image](https://cloud.githubusercontent.com/assets/9439053/12043054/8edb3cb4-ae46-11e5-9702-b2d3c74aae18.png)

**Comment by savance-ford** [comment]
Media query to remove logo on small screens

**Comment by kathyoleary** [comment]
https://github.com/adorableio/LMHT/pull/34 Submitted for thumbs.

**Comment by kathyoleary** [comment]
Thumbs in, merge done, branch deleted.
