### ISSUE TITLE
Edit Spanish text to match the audio (3 small edits)

### ISSUE THREAD

**Issue by JenEEsquivel** [kevinbrianfahy/LMHT#143]
1.  In the "footer" tag, the Spanish translation should read "El Pie de Página" (adds the word El before Pie)
2. In the "br" tag, "El br etiqueta" (first line of the definition in Spanish) should be changed to "La etiqueta br"
3. In the "base" tag, the Spanish definition that reads "todos los URL relativos" should be changed to "todos los URLs relativos" (plural for URL)

**Comment by ericanaughton** [comment]
From Jen: "I will need to move three minor edits to the next sprint.  The edits are single word changes in Spanish text to match audio.  ["URL" changed to "URLs" in base tag Spanish definition, "El etiqueta" changed to La etiqueta" in the br tag, and add El before "Pie de Pagina" Spanish translation on the footer page "El Pie de Pagina"]   I will have these completed this week and can work on the new tag translations for the next sprint."

**Comment by kathyoleary** [comment]
Put out there for thumbs https://github.com/adorableio/LMHT/pull/40

**Comment by JenEEsquivel** [comment]
Double thumbs.  Merged, closed, deleted branch.
