### ISSUE TITLE
English - Create <h1> - <h6> elements

### ISSUE THREAD

**Issue by kathyoleary** [kevinbrianfahy/LMHT#145]
In order to learn more elements,
As an LMHT user,
I want to be able to look up and learn about the header elements.

Acceptance Criteria:
The english text sections of the standard element page will be completed for `<h1> - <h6>`.
Combine all 6 under one page - use sample coding to show the difference in size as they are otherwise identical.

Given any LMHT user,
I want to select  and find the `<h1> - <h6>` element page
Where I can learn about the element in english.

**Comment by kathyoleary** [comment]
```
<h1-h6>
```

English base: Headers

Definition: Not to be confused with the `<header>` element which is a whole section of a web page:  heading elements are used to describe the topic or give the title of the section it is introducing.  There are six graduated levels of font size and boldness with `<h1>` being the largest and boldest down to `<h6>` as the smallest and least boldface.   

How to Remember: In a concert, the number one artist headlining in the show is the biggest and brightest, the second in importance is slightly smaller and under the headliner, and so on down the line--
just as heading level 1 < h1 > is the biggest and boldest, heading level 2 < h2 > is slightly smaller and less bold, and so on down the line.

Code example:
`<h1>William Shakespeare</h1>`
`<h2>William Shakespeare Biography</h2>`
`<h2>The Works of William Shakespeare</h2>`
`<h3>Shakespeare’s Poems and Sonnets</h3>`
`<h3>Shakespeare’s Plays</h3>`
`<h4>Romeo and Juliet</h4>`
`<h5>Act I</h5>`
`<h5>Act II</h5>`
`<h5>Act III</h5>`
`<h5>Act IV</h5>`
`<h5>Act V</h5>`

**Comment by JenEEsquivel** [comment]
:+1: Nice. Is the line break between "the" and "element" in the definition just a Github quirk? 
Possible edit for clarity (?): In a concert, the number one artist headlining in the show is the biggest and brightest, the second in importance is slightly smaller and under the headliner, and so on down the line--
just as heading level 1 &lt; h1 &gt; is the biggest and boldest, heading level 2 &lt; h2 &gt; is slightly smaller and less bold, and so on down the line."

**Comment by kathyoleary** [comment]
https://github.com/adorableio/LMHT/pull/52  Sent up.
