### ISSUE TITLE
English - Create <div> element

### ISSUE THREAD

**Issue by kathyoleary** [kevinbrianfahy/LMHT#146]
In order to learn more elements,
As an LMHT user,
I want to be able to look up and learn about the division element.

Acceptance Criteria:
The english text sections of the standard element page will be completed for `<div>`.

Given any LMHT user,
I want to select  and find the `<div>` element page
Where I can learn about the element in english.

**Comment by kathyoleary** [comment]
```
<div>
```

English base: Divider

Definition:  An all purpose, generic container for web page content.  There are different containers such as header, footer, nav, section that are for specific sections of the web page.  The div container is used when none of these apply.  You group content together in containers when you want to style the content in it the same way. 

How to Remember:  Div is used to divide your web page into similarly styled sections.

Code example:

```
<div class=“chapter-list”>
<ul>
    <li>
        <p>Chapter One:  Welcome to Coding</p>
    </li>
    <li>
        <p>Chapter Two:  Fundamentals of a Computer</p>
    </li>
</ul>
```

**Comment by rylnd** [comment]
Definition: An all-purpose, generic container for web content. There are more specific containers (header, footer, nav, section, etc.) for more specific use cases. If you're grouping content for generic purposes like styling or simply logical grouping, use a div.

**Comment by rylnd** [comment]
I would maybe add another type of element in the div, to solidify the 'grouping' aspect:

``` html
<div class="table-of-contents">
  <h4>Table of Contents</h4>
  <ul>
    <li>
        <p>Chapter One:  Welcome to Coding</p>
    </li>
    <li>
        <p>Chapter Two:  Fundamentals of a Computer</p>
    </li>
  </ul
</div>
```

**Comment by kathyoleary** [comment]
https://github.com/adorableio/LMHT/pull/53  Sent up

**Comment by kathyoleary** [comment]
Whoops will add Ryland's and resend.  Just saw that.  I was working without a wifi connection for a bit last night

**Comment by kathyoleary** [comment]
Ok, I changed the definition but I am holding back on adding another element to the div because I want the example to not get too cumbersome or involved.  Just a basic example of what a div would look like as opposed to showing multiple examples and different variations as some of these we could really go hog wild on showing all the variations.  Going for smaller, simpler but still showing what it is.
