### ISSUE TITLE
English - Create <li> element.

### ISSUE THREAD

**Issue by kathyoleary** [kevinbrianfahy/LMHT#149]
In order to learn more elements,
As an LMHT user,
I want to be able to look up and learn about the list item element.

Acceptance Criteria:
The english text sections of the standard element page will be completed for `<li>`.

Given any LMHT user,
I want to select  and find the `<li>` element page
Where I can learn about the element in english.

**Comment by kathyoleary** [comment]
```
<li>
```

English base: List item

Definition:  A child element that is an item in a list.  The `<li>` must be in a parent container either: an ordered list `<ol>`, unordered list `<ul>` or menu `<menu>`.  In menus and unordered lists, each list item is usually separated by bullet points and in ordered lists they are separated in ascending or descending order using letters or numbers.

How to Remember:  A list item can be as simple as a grocery list to as complicated as directions on how to build a website.  

Code example:

```
<ol start = “1">
    <li>Heat a cup of milk on the stove</li>
    <li>Put it in a mug</li>
    <li>Add 3 heaping tablespoons of cocoa mix</li>
</ol>
```

**Comment by rylnd** [comment]
How to Remember: A list item can be as simple as **an item on** a grocery list or as complicated as **a step in** directions on how to build a website.

**Comment by kathyoleary** [comment]
https://github.com/adorableio/LMHT/pull/56  Sent up with Ryland's change already in it.
