### ISSUE TITLE
English - Create <em> element.

### ISSUE THREAD

**Issue by kathyoleary** [kevinbrianfahy/LMHT#150]
In order to learn more elements,
As an LMHT user,
I want to be able to look up and learn about the emphasis (usually italic) element.

Acceptance Criteria:
The english text sections of the standard element page will be completed for `<em>`.

Given any LMHT user,
I want to select  and find the `<em>` element page
Where I can learn about the element in english.

**Comment by kathyoleary** [comment]
```
<em>
```

English base: emphasis

Definition:  Element used to stress emphasis or show priority or force on a particular section of text.  Used to make a particular section of text stand out from its surrounding text.  It usually changes the selected text to italics to show the emphasis.

How to Remember:  Emotion also starts with em and emphasis means putting extra emotion into that section of text.

Code example:

```
<p>
    I repeat….I will <em>NOT</em> clean my room!
</p>
```

**Comment by rylnd** [comment]
I would either explain or remove the sentence about "usually chang[ing] ... to italics."

The description for `<strong>` in #152 does a good job of explaining the semantic difference between `<strong>` (logical state) vs `<b>` (physical state); we could do the same here.

**Comment by kathyoleary** [comment]
Definition:  Element used to stress emphasis or show priority or force on a particular section of text.  Used to make a particular section of text stand out from its surrounding text.  It usually changes the selected text to italics to show the emphasis.

Changed to: 

Definition:  Element used to stress emphasis or show priority or force on a particular section of text so it stands out from its surrounding text.  Emphasis is a logical state meaning it uses physical state changes to change the text.  As it's logical, it can be one physical change or mutliple.  Emphasis usually changes the selected text to italics.  It does not need to be the same for every website.  Example:  You could set up emphasis for a document on quitting smoking to always assign multiple physical changes on the words "Stop smoking now!" where it is in italics, font-color of royal blue and always underlined.

**Comment by kathyoleary** [comment]
https://github.com/adorableio/LMHT/pull/57  Sent up.
