### ISSUE TITLE
English - Create <strong> element.

### ISSUE THREAD

**Issue by kathyoleary** [kevinbrianfahy/LMHT#151]
In order to learn more elements,
As an LMHT user,
I want to be able to look up and learn about the strong emphasis (usually bold) element.

Acceptance Criteria:
The english text sections of the standard element page will be completed for `<strong>`.

Given any LMHT user,
I want to select  and find the `<strong>` element page
Where I can learn about the element in english.

**Comment by kathyoleary** [comment]
```
<strong>
```

English base: Strong emphasis

Definition:  Element used to indicate importance of selected text usually by putting it in bold print.  `<b>` boldface can also be used however `<strong>` is considered a logical state and `<b>` bold is a physical state.  In CSS, it is more logical to assign attributes to `<strong>` text to separate it and show emphasis, including assigning the physical attribute of being `<b>` boldface text as well as other attributes such as font-size or font-color.

How to Remember:  Text in boldface shows strong emotion as its darker and bolder than its surrounding text.

Code example:

```
<p>
    I am <strong>THE GREATEST</strong> future web designer ever!
</p>
```

**Comment by vannrod** [comment]
Definition: The `<strong>` element is used to indicate the importance of selected text and is typically displayed in boldface. Boldface `<b>` can also be used, but `<strong>` is considered a logical state and `<b>` is a physical state. The logical state allows for `<strong>` text to be expressed in many different ways including different colors or size, underlined, or whatever.

How to Remember: When you want to make a `<strong>` argument, it is important to have it standout and you can do so by changing text color and boldfacing it.

**Comment by kathyoleary** [comment]
https://github.com/adorableio/LMHT/pull/59  sent up
