### ISSUE TITLE
English - Create <b> element.

### ISSUE THREAD

**Issue by kathyoleary** [kevinbrianfahy/LMHT#152]
In order to learn more elements,
As an LMHT user,
I want to be able to look up and learn about the boldface text element.

Acceptance Criteria:
The english text sections of the standard element page will be completed for `<b>`.

Given any LMHT user,
I want to select  and find the `<b>` element page
Where I can learn about the element in english.

**Comment by kathyoleary** [comment]
```
<b>
```

English base: Boldface

Definition: Originally, `<b>` was meant to make text boldface.  Currently, it used to indicate section of text that is styled differently from other text.  However, it is recommended to use `<em>, <strong> or <mark>` when indicating important text and why it is important.  The `<b>` element is usually used when these don’t work well for the situation or to indicate keywords, product names and other text that needs to be boldfaced to stand out but does not have any emphasis on the text.

How to Remember:  `<b>` is now considered the old version of bold.  It is `"<b>old”` school way of getting boldface text.

Code example:

```
<p>
    The <b>LMHT</b> page can be found on <b>Github.com</b>.
</p>
```

**Comment by vannrod** [comment]
Definition: Originally, `<b>` was meant to make text boldface. Currently, it used to indicate a section of text that is styled differently from other text. The `<b>` element is usually used when other command codes don’t work well for the situation. It is also used to indicate keywords, product names, and other text that need to stand out but do not have any emphasis on the text. It is strongly recommended to use `<em>`, `<strong>` or `<mar>` when indicating important text.

How to Remember: `<b>` is now considered the old version of bold. It is the `<b>old` school way of getting boldface text.

**Comment by kathyoleary** [comment]
https://github.com/adorableio/LMHT/pull/61  Sent up.
