### ISSUE TITLE
English - Create <i> element.

### ISSUE THREAD

**Issue by kathyoleary** [kevinbrianfahy/LMHT#153]
In order to learn more elements,
As an LMHT user,
I want to be able to look up and learn about the italic text element.

Acceptance Criteria:
The english text sections of the standard element page will be completed for `<i>`.

Given any LMHT user,
I want to select  and find the `<i>` element page
Where I can learn about the element in english.

**Comment by kathyoleary** [comment]
```
<i>
```

English base: Italic

Definition:  The italic element is used to indicate text that needs to stand apart from its surrounding text.  The most common uses are:  technical terms, foreign language, conversation or thoughts of characters in fictional stories or just as a way to add stress to a particular word or text.

How to Remember:  I is for interesting as well as italic and the `<i>` element is used to make interesting things stand apart by italicizing it.

Code example:

```
<p> Nelson Mandela said: <i>”If you talk to a man in a language he understands, that goes to his head.  If you talk to him in his own language, that goes to his heart.”</i>
```

**Comment by vannrod** [comment]
Definition: The < i > element is used to indicate text that needs to stand apart from its surrounding text. The most common uses are: technical terms, foreign language, conversation or thoughts of characters in fictional stories, or just as a way to stress a particular word or text.

How to Remember: I is for interesting as well as italic, the < i > element is used to make interesting things stand apart.

(Wrote the i element with spaces so it wouldn't italicize, you get the picture.)

**Comment by kathyoleary** [comment]
https://github.com/adorableio/LMHT/pull/62  sent up.
