### ISSUE TITLE
Welcome Section is broken

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#177]
PR https://github.com/LMHT/LMHT.github.io/pull/176 is blocked until this is fixed.

When you open the LMHT site locally, the Welcome section does not show.

![image](https://cloud.githubusercontent.com/assets/9439053/12152703/9663e464-b47b-11e5-9231-f6df484944fc.png)

**Comment by kathyoleary** [comment]
https://github.com/adorableio/LMHT/pull/39  submitted for thumbs

**Comment by kathyoleary** [comment]
done and merged
