### ISSUE TITLE
Add rules to linter

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#180]
In order to maintain standards and consistency
As a developer of LMHT
I want to have rules for spaces within and around parenthesis be consistent.

Acceptance Criteria:
- Adds a space after `if`. Ex: `if(Charlie)` should be `if (Charlie)`
- Removes extra spaces between parenthesis. Ex: `( Charlie )` should be `(Charlie)`

As a developer of LMHT
When I am contributing to the project
I want to know what the standards are for code
And I want to be given feedback from the linter
Before I get my PR reviewed.

**Comment by kathyoleary** [comment]
Do not know if this will affect linter, but we need to also look at https://css-tricks.com/autoprefixer/ as we are using flexbox and that is affected a lot by changes in web browsers updating their code on how to deal with what we are using.  Need to integrate this or something similar to handle that.

**Comment by kathyoleary** [comment]
Added "computed-property-spacing" to remove the extra spaces however there isn't a rule to add the space in an "if" statement.

**Comment by rylnd** [comment]
@kathyoleary see http://eslint.org/docs/rules/space-before-blocks and http://eslint.org/docs/rules/keyword-spacing; I would not close this until those rules are enabled.

**Comment by kathyoleary** [comment]
Updated all this under https://github.com/LMHT/LMHT.github.io/issues/71

**Comment by rylnd** [comment]
@kathyoleary what about https://github.com/LMHT/LMHT.github.io/issues/180#issuecomment-227554737 ?

**Comment by kathyoleary** [comment]
Those are automatically enabled with the linter recommended loaded at the top, according to the eslint page at least

**Comment by rylnd** [comment]
I am able to do something like 

``` js
if(bla){
  foo();
}
```

and the linter does not complain. Are you seeing different behavior?

**Comment by kathyoleary** [comment]
let me check, if so then even more of their documentation is incorrect or we need to see why its not behaving right.

**Comment by rylnd** [comment]
Their documentation looks correct to me; the two rules in question have 'wrenches' (not check marks) proceeding them, which means that they support the `--fix` option, not that they are enabled by default.

**Comment by kathyoleary** [comment]
OK, 

this one got messy fixing it across two PR's.  But had to open new one to do the rest of the work.  It's fixed under https://github.com/adorableio/LMHT/pull/72 with the rest of the requests.
