### ISSUE TITLE
Spanish text edits on Welcome page

### ISSUE THREAD

**Issue by JenEEsquivel** [kevinbrianfahy/LMHT#183]
In order to understand the Spanish text,
As an LMHT user,
I want to read proper Spanish translations.

Acceptance Criteria:
On the Welcome page, the Spanish text has minor spelling changes and edits
in the "Como utlizar LMHT" section.
1. selecció should be selección (add n)
2. informació should be información (add n)
3. Inglé should be Inglés (add s)
4. There should be a period at the end (after código)

Given any Spanish-speaking LMHT user,
I want to be able to read and understand the Spanish text,
without having to translate the English side to understand what is being written.

**Comment by JenEEsquivel** [comment]
Waiting on two thumbs up. https://github.com/adorableio/LMHT/pull/41

**Comment by kathyoleary** [comment]
Got thumbs and merged, deleted etc.
