### ISSUE TITLE
Search bar changes horizontal position on wider screens

### ISSUE THREAD

**Issue by rylnd** [kevinbrianfahy/LMHT#188]
It's not noticeable at smaller widths, but at ~1000px viewport, switching between the absolute and fixed search bar causes the input itself to shift horizontally. The main difference is the presence/absence of the LMHT logo, so I'm guessing it's got something to do with that.

It's obviously not a _huge_ deal, but it does take away from the 'smoothness' of the search bar.

**Comment by kathyoleary** [comment]
Switched to https://github.com/LMHT/LMHT.github.io/issues/198

Didn't realize it was a duplicate and the other one has the pics, and an additional issue with the search bar.

**Comment by rylnd** [comment]
While this issue and #198 are probably caused by the same thing, I feel that, as stated, #198 does not explicitly cover this case (the slight horizontal shift when you scroll down past the fixed search bar). Could you please update its description so that this specific issue is not overlooked?

**Comment by kathyoleary** [comment]
Updated to include and also reference this one.
