### ISSUE TITLE
Audio play buttons are broken on LMHT.github.io

### ISSUE THREAD

**Issue by bigtiger** [kevinbrianfahy/LMHT#190]
I'm not sure what's happening.

When I load a page like http://lmht.github.io/#br I expect to see multiple play buttons

One each for the english and spanish base word and definitions.

When I click the button I expect to hear them play audio.

**Comment by ericanaughton** [comment]
@SaVanceX I've been looking into how this came to be. Not sure what happened yet. Any ideas?

**Comment by ericanaughton** [comment]
fixed and merged to adorable master
