### ISSUE TITLE
Written Spanish Translation for <meta>

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#34]
- spanish word equivalent
- definition
- how to remember

**Comment by mostlybadfly** [comment]
working on this one.

**Comment by ericanaughton** [comment]
https://github.com/LMHT/LMHT.github.io/pull/64 has two thumbs. then jen gave a suggestion, daniel agreed to correct it. he planned on using the same PR. we can wait til he adds the correction. or we can merge what is already done.

**Comment by JenEEsquivel** [comment]
:+1: (#34 on--> #64)
