### ISSUE TITLE
Contributing.md

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#42]
Need to create a document with suggestions for outside contributors, to keep things running smoothly.

for example: https://github.com/rails/rails/blob/master/CONTRIBUTING.md

**Comment by ericanaughton** [comment]
Kathy & Jen plan to finish this for the current sprint

**Comment by kathyoleary** [comment]
https://drive.google.com/a/adorable.io/file/d/0BwOijbndnWZLeWtvZkV1QS1WekU/view?usp=sharing

half-way finished - updating the rest

**Comment by ericanaughton** [comment]
good work @kathyoleary

**Comment by kathyoleary** [comment]
Sent it out for thumbs up

**Comment by ericanaughton** [comment]
PR is out there: https://github.com/adorableio/LMHT/pull/3
but changes need to be made based on feedback given. @kathyoleary

**Comment by kathyoleary** [comment]
Did the rest of the changes and resubmitted for double thumbs up

**Comment by ericanaughton** [comment]
this has been merged to adorable master.
