### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#43]
provide guidance for beginners on how to use github

for example: https://github.com/boutbitnz/Mad_Discovery

**Comment by ericanaughton** [comment]
Kathy & Jen plan to finish this for the current sprint

**Comment by JenEEsquivel** [comment]
Added comments and additions to the README.md google docs file.

**Comment by kathyoleary** [comment]
https://drive.google.com/a/adorable.io/file/d/0BwOijbndnWZLVjluNm81T1NBQnc/view?usp=sharing

Will update the last section with the new email address so people can contact with issues as needed

**Comment by kathyoleary** [comment]
Sent it out for thumbs up

**Comment by ericanaughton** [comment]
@kathyoleary next time, you can put a link to the PR here :) 
https://github.com/adorableio/LMHT/pull/4

**Comment by kathyoleary** [comment]
Got a thumbs up and a conditional thumbs up, didn't realize the changes had to be done with the conditional were attached, merged.  Annalise submitted a change, but her changes had an error so I sent a request back to her to do the change and either resubmit on master or on the original branch and just let me know so I can finish it up.  Waiting for her to send the resubmit.

**Comment by kathyoleary** [comment]
sent the changes myself and put out the double thumbs up request

**Comment by ericanaughton** [comment]
this has been merged to adorable master.
