### ISSUE TITLE
Fix URL's for each element

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#44]
In order to easily share a link to a specific page of LMHT,
As a LMHT user,
I want the page I'm sharing to have a shorter link.

Acceptance Criteria:
- The '.html' is removed from the URL
- The new URL link works

Given a LMHT user,
When I want to share a specific page of LMHT,
I can use a URL that is short enough to remember.

**Comment by ericanaughton** [comment]
Note: To get rid of .html, check out these references
https://www.geekshosted.com/Blog/how-to-remove-html-from-your-url/
http://alexcican.com/post/how-to-remove-php-html-htm-extensions-with-htaccess/

**Comment by kathyoleary** [comment]
https://github.com/adorableio/LMHT/pull/19

Under construction - need to test it before merging it.

**Comment by kathyoleary** [comment]
OK,....further fixes I need to do before merging this...

going to separate out the other fixes to a separate PR, they're going to take more time.

The two issues will be put on other Issues are:  typing in page and hitting enter does not reliably bring the page up, you have to refresh for it to always work, but it does sometimes work.  No reliable way to always recreate the issue.

Also working on removing the hashtag from the url

**Comment by ericanaughton** [comment]
@kathyoleary i dont understand the first point. when i refresh the page, i dont expect a new page to appear. am i missing something?

**Comment by kathyoleary** [comment]
If I bring up the site, and remove welcome and replace it with footer and hit enter, it does not bring up the footer page, you have to hit refresh page for it to bring it up.  I want to see if we can get it to open up upon hitting enter.

**Comment by kathyoleary** [comment]
OK, merged https://github.com/adorableio/LMHT/pull/19 and that removed the .html from the page.  The hash tag removal has been listed as blocked per Kevin - server issue not allowing us to do it.  and we cannot reliably recreate the enter button not working so until we can recreate it regularly we can't fix it.  Closing this issue because everything that could be done is done, the ones that are not are under new issues and listed blocked.
