### ISSUE TITLE
Links for advanced resources

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#45]
In order to further my learning,
As an English or Spanish HTML learner,
I want access to advanced resources.

Acceptance Criteria:
- Links to other sites work when you click them
- The resources we recommend are quality sites, such as MDN
- A statement such as, "Ready to further your learning?.." is used 
- These resources a visible in a way that's not overwhelming or cluttered

Given an English or Spanish HTML learner,
When I am ready to deepen my learning in HTML,
I want quick access to recommended advanced resources.

**Comment by kathyoleary** [comment]
https://github.com/adorableio/LMHT/pull/48  Sent this up. Waiting for thumbs.
