### ISSUE TITLE
Welcome Section - English

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#46]
Add a section that gives an explanation for the site, how to use it, etc.

This can be placed in a container that resembles the layout of the definitions.

This can be in view before the user chooses an element.

Currently, with the dropdown list, the Welcome Section could be placed under the 'select a tag' feature.  When the combo box replaces the drop down list, it can be displayed in the same place, before an element is chosen.

**Comment by ericanaughton** [comment]
This needs to be on the next sprint (11/30)

**Comment by kathyoleary** [comment]
https://drive.google.com/open?id=1p-jCCESHQMdtaBH29IVLqgtaS0WcBBLhlb2Apsgg3BU

Here's the initial setup for the Welcome Section.  I wanted to do it on my shared drive first and just get immediate team feedback first, before putting it out on a pull request and getting the whole team feedback.  Going for it being on an element.html page and it will show as the placeholder page when you open up the website.

**Comment by ericanaughton** [comment]
@kathyoleary how is this going?

**Comment by kathyoleary** [comment]
Finished what I could, put out an under construction Pull Request  - need spanish translations completed and those already in there reviewed for typos...there _are_ typos...

https://github.com/adorableio/LMHT/pull/9

**Comment by ericanaughton** [comment]
merged to adorable master
