### ISSUE TITLE
reword 'base word'

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#48]
Kathy did a mock up and talked to Jim about changing:

'English base word' to 'English base'
and
'Spanish Equivalent Word' to 'Spanish translation/Traducción en Español'

This will eliminate all the singular/plural talk as well as providing a more accurate description of what each is.

**Comment by kathyoleary** [comment]
PR#53 is waiting for double thumbs and should fix this.  Just FYI also put new trello board up because the spanish side does not say Spanish Words Equivalent and that sounds funny anyways.

**Comment by ericanaughton** [comment]
Kathy plans to finish this for the current sprint

**Comment by kathyoleary** [comment]
Kathy did finish this for the current sprint.  Yay Kathy!  Woot!
