### ISSUE TITLE
Create ribbon for 'Contribute Here'

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#63]
@bigtiger, back in the day, you gave feedback about having the contributing info emphasized and easy to see right away. @SaVanceX made a wireframe (maybe about a month ago) with that info placed above the current audio player. Do you prefer to have that contributing info displayed on the site always? Or is it good enough to have it in the Welcome Section?  We also talked about using a 'ribbon' in the corner, that linked people straight to our Github repo.

**Comment by kathyoleary** [comment]
https://github.com/adorableio/LMHT/pull/9  I removed the footer info in this one.  So now just need to relocate that info if you want it elsewhere..

**Comment by ericanaughton** [comment]
@bigtiger likes the ribbon. "Contribute" on the ribbon. When clicked, it links to the instructions for contributing.

**Comment by ericanaughton** [comment]
merged to adorable master
