### ISSUE TITLE
Remove all unused branches

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#74]
- [x] Adorable repo
- [x] LMHT repo

**Comment by ericanaughton** [comment]
didn't get to it this sprint

**Comment by ericanaughton** [comment]
Branches in LMHT that I'm not sure about:

'Credits' --> Gives credit to Sandra for the README. This branch was not merged to master.  I messaged sandra & kevin to see if they want it merged, and letting them know it would be updated, if so.

'Gh-pages-old' --> Last commit contains gulpfile addition (in Sept by Chris Coyier).  115 commits behind master. I messaged him to see if it's okay to delete.

'Url-updater' --> Last commit updates JS to change URL with element (in Aug by Chris C.). Messaged him.

**Comment by kathyoleary** [comment]
The Credits branch can be deleted actually, we have completely replaced that readme file with something totally different.

**Comment by ericanaughton** [comment]
Deleted 'gh-pages-old', 'url-updater', 'add_gulp' (got the okay from chris). Going to wait a day on response from Sandra/Kevin about 'credits' before taking action.

**Comment by kathyoleary** [comment]
Did you see the comment I put in on the credits one?  That readme file has
been totally replaced so what's in there doesn't even matter anymore.
Should be able to delete it.

**Comment by ericanaughton** [comment]
I deleted the 'credits' from the Adorable master because it does not pertain to us. However, I am not deleting it from the LMHT master right away, in case Sandra still wants credit for her contribution to the README.
