### ISSUE TITLE
Cleanup all the code

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#96]
In order to use best practices
As a contributor to LMHT,
I want to cleanup all the code.

Acceptance Criteria:
- In CSS, all styles are alphabetized in each class
- In CSS, all classes are in order, relating to where they are in HTML
- All indentation is consistent (2 spaces)
- Make sure all the HTML/CSS is DRY

Given a contributor to LMHT,
When I search through the code,
I am able to easily find what I'm looking for
Because everything is tidy, consistent and in order.

**Comment by ericanaughton** [comment]
PR ready for review https://github.com/adorableio/LMHT/pull/15

**Comment by kathyoleary** [comment]
Updated and did the rest of the cleanup https://github.com/adorableio/LMHT/pull/15  Put out for two thumbs up.

**Comment by ericanaughton** [comment]
merged
