### ISSUE TITLE
update accent marks for spanish text

### ISSUE THREAD

**Issue by ericanaughton** [kevinbrianfahy/LMHT#98]
https://github.com/LMHT/LMHT.github.io/pull/92 needs two thumbs
https://github.com/LMHT/LMHT.github.io/pull/91 needs two thumbs
https://github.com/LMHT/LMHT.github.io/pull/90 needs two thumbs
https://github.com/LMHT/LMHT.github.io/pull/89 needs two thumbs
https://github.com/LMHT/LMHT.github.io/pull/87 needs one thumb
https://github.com/LMHT/LMHT.github.io/pull/85 needs one thumb

**Comment by JenEEsquivel** [comment]
I checked the ones I hadn't already.  They need a second, now.
#92 needs one thumb
#91 needs one thumb
#90 needs one thumb
#89 needs one thumb
#87 needs one thumb
#85 needs one thumb
